# Generated by Django 3.2.9 on 2022-03-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('passw', models.CharField(max_length=20)),
                ('reppass', models.CharField(max_length=20)),
            ],
        ),
    ]
